package com.garanti.insurancequote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Decision implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "uwDecision")
	private java.lang.String uwDecision;

	public Decision() {
	}

	public java.lang.String getUwDecision() {
		return this.uwDecision;
	}

	public void setUwDecision(java.lang.String uwDecision) {
		this.uwDecision = uwDecision;
	}

	public Decision(java.lang.String uwDecision) {
		this.uwDecision = uwDecision;
	}

}