package com.garanti.insurancequote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Decision implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Decision() {
    }




}